package com.firstbank.uganda.controllers.database;

import com.firstbank.uganda.models.account.Account;
import com.firstbank.uganda.models.customer.Customer;

import java.sql.*;
import java.time.LocalDateTime;

public class DatabaseController {
    
    // HSQLDB embedded database - creates file in project folder
    private static final String DB_URL = "jdbc:hsqldb:file:./bankdata;shutdown=true";
    private static final String DB_USER = "SA";
    private static final String DB_PASSWORD = "";
    
    private Connection connection;
    private boolean isConnected;
    
    public DatabaseController() {
        this.isConnected = false;
        System.out.println("Initializing DatabaseController...");
        connect();
    }
    
    private void connect() {
        try {
            // Load HSQLDB driver
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            System.out.println("HSQLDB driver loaded successfully!");
            
            // Connect to database
            connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
            isConnected = true;
            System.out.println("✅ Database connected successfully!");
            
            // Create table
            createTableIfNotExists();
            
        } catch (ClassNotFoundException e) {
            System.err.println("HSQLDB driver not found!");
            isConnected = false;
        } catch (SQLException e) {
            System.err.println("Database connection failed: " + e.getMessage());
            isConnected = false;
        }
    }
    
    private void createTableIfNotExists() {
        String sql = """
            CREATE TABLE IF NOT EXISTS Accounts (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                accountNumber VARCHAR(50) UNIQUE NOT NULL,
                accountType VARCHAR(20) NOT NULL,
                firstName VARCHAR(30) NOT NULL,
                lastName VARCHAR(30) NOT NULL,
                nin VARCHAR(14) NOT NULL,
                email VARCHAR(100) NOT NULL,
                phoneNumber VARCHAR(20) NOT NULL,
                pin VARCHAR(6) NOT NULL,
                dateOfBirth DATE NOT NULL,
                branch VARCHAR(30) NOT NULL,
                openingDeposit DOUBLE NOT NULL,
                currentBalance DOUBLE DEFAULT 0,
                accountStatus VARCHAR(20) DEFAULT 'ACTIVE',
                registrationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """;
        
        try (Statement stmt = connection.createStatement()) {
            stmt.execute(sql);
            System.out.println("Table 'Accounts' verified/created.");
        } catch (SQLException e) {
            System.err.println("Table creation failed: " + e.getMessage());
        }
    }
    
    public boolean saveAccount(Account account) {
        if (!isConnected) {
            System.err.println("Database not connected. Cannot save.");
            return false;
        }
        
        Customer customer = account.getCustomer();
        String sql = "INSERT INTO Accounts (" +
            "accountNumber, accountType, firstName, lastName, nin, email, " +
            "phoneNumber, pin, dateOfBirth, branch, openingDeposit, currentBalance, accountStatus" +
            ") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, account.getAccountNumber());
            ps.setString(2, account.getAccountType());
            ps.setString(3, customer.getFirstName());
            ps.setString(4, customer.getLastName());
            ps.setString(5, customer.getNin());
            ps.setString(6, customer.getEmail());
            ps.setString(7, customer.getPhoneNumber());
            ps.setString(8, customer.getPin());
            ps.setDate(9, Date.valueOf(customer.getDateOfBirth()));
            ps.setString(10, customer.getBranch());
            ps.setDouble(11, account.getBalance());
            ps.setDouble(12, account.getBalance());
            ps.setString(13, "ACTIVE");
            
            int rows = ps.executeUpdate();
            System.out.println("✅ Account saved to database successfully!");
            return rows > 0;
            
        } catch (SQLException e) {
            System.err.println("Save failed: " + e.getMessage());
            return false;
        }
    }
    
    public Account getAccount(String accountNumber) {
        if (!isConnected) return null;
        
        String sql = "SELECT * FROM Accounts WHERE accountNumber = ?";
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            ps.setString(1, accountNumber);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                Customer customer = new Customer(
                    rs.getString("firstName"),
                    rs.getString("lastName"),
                    rs.getString("nin"),
                    rs.getString("email"),
                    rs.getString("phoneNumber"),
                    rs.getString("pin"),
                    rs.getDate("dateOfBirth").toLocalDate(),
                    rs.getString("accountType"),
                    rs.getString("branch"),
                    rs.getDouble("openingDeposit")
                );
                
                Account account = AccountFactory.createAccount(
                    rs.getString("accountType"), customer
                );
                if (account != null) {
                    account.setBalance(rs.getDouble("currentBalance"));
                }
                return account;
            }
        } catch (SQLException e) {
            System.err.println("Get account failed: " + e.getMessage());
        }
        return null;
    }
    
    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                // HSQLDB shutdown
                Statement stmt = connection.createStatement();
                stmt.execute("SHUTDOWN");
                connection.close();
                System.out.println("Database connection closed.");
            }
        } catch (SQLException e) {
            System.err.println("Error closing connection: " + e.getMessage());
        }
    }
    
    public boolean isConnected() { return isConnected; }
}
